### ISSUE TITLE
新的crypto RSS订阅推荐

### ISSUE THREAD

**Issue by Lyther** [zer0yu/CyberSecurityRSS#12]
贵安，

希望能增加一项我个人日常订阅的优质blog，包含密码学与区块链的高质量文章。

目标页面：https://vitalik.ca/

RSS订阅：https://vitalik.ca/feed.xml

**Comment by zer0yu** [comment]
感谢推荐，已经在今天的更新中加入。如有优质RSS订阅源欢迎继续推荐
